[package]
name = "bayonese_server_example"
version = "0.1.0"
edition = "2021"

[dependencies]
bayonese = { path = "../bayonese_rust" }
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
bayonese_py = { path = "../client_python" }